<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-sky-700">Reservas</p><h2 class="text-2xl font-bold tracking-tight text-slate-900">Confirmar reserva</h2></div><div class="flex items-center gap-2 text-sm text-slate-500"><span class="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-500 text-xs font-bold text-white">✓</span><span class="h-px w-6 bg-slate-300"></span><span class="flex h-7 w-7 items-center justify-center rounded-full bg-sky-600 text-xs font-bold text-white">2</span><span>Confirmação</span></div></div></x-slot>
    <div class="py-8 sm:py-10"><div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><form action="{{ route('reservations.store') }}" method="POST" class="grid gap-6 lg:grid-cols-5">@csrf
        <input type="hidden" name="room_id" value="{{ $room->id }}"><input type="hidden" name="check_in" value="{{ $data['check_in'] }}"><input type="hidden" name="check_out" value="{{ $data['check_out'] }}"><input type="hidden" name="adults" value="{{ $data['adults'] }}"><input type="hidden" name="children" value="{{ $data['children'] ?? 0 }}">
        <section class="lg:col-span-3 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-100 text-xl font-bold text-sky-700">1</div><h3 class="mt-4 text-lg font-bold text-slate-900">Hóspede principal</h3><p class="mt-1 text-sm text-slate-500">Selecione a pessoa responsável pela reserva.</p>
            @if ($errors->has('room_id') || $errors->has('database_error'))<div class="mt-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $errors->first('room_id') ?: $errors->first('database_error') }}</div>@endif
            <div class="mt-6"><label for="guest_id" class="mb-2 block text-sm font-semibold text-slate-700">Hóspede</label><select id="guest_id" name="guest_id" required class="block w-full rounded-lg border-slate-300 shadow-sm focus:border-sky-500 focus:ring-sky-500"><option value="">Selecione um hóspede</option>@foreach ($guests as $guest)<option value="{{ $guest->id }}" @selected(old('guest_id') === $guest->id)>{{ $guest->full_name }}{{ $guest->document_number ? ' — '.$guest->document_number : '' }}</option>@endforeach</select>@error('guest_id')<p class="mt-2 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
            <p class="mt-5 rounded-lg bg-slate-50 px-4 py-3 text-sm text-slate-500">Não encontrou o hóspede? <a href="{{ route('guests.create') }}" class="font-semibold text-sky-700 hover:text-sky-800">Cadastrar novo hóspede</a>.</p>
        </section>
        <aside class="lg:col-span-2 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="bg-slate-900 px-6 py-5 text-white"><p class="text-xs font-semibold uppercase tracking-wider text-sky-200">Resumo da estadia</p><h3 class="mt-1 text-xl font-bold">Quarto {{ $room->number }}</h3><p class="text-sm text-slate-300">{{ $room->roomType->name }}</p></div><dl class="divide-y divide-slate-100 px-6"><div class="flex justify-between py-4"><dt class="text-sm text-slate-500">Check-in</dt><dd class="text-sm font-semibold text-slate-800">{{ \Carbon\Carbon::parse($data['check_in'])->format('d/m/Y') }}</dd></div><div class="flex justify-between py-4"><dt class="text-sm text-slate-500">Check-out</dt><dd class="text-sm font-semibold text-slate-800">{{ \Carbon\Carbon::parse($data['check_out'])->format('d/m/Y') }}</dd></div><div class="flex justify-between py-4"><dt class="text-sm text-slate-500">Hospedagem</dt><dd class="text-sm font-semibold text-slate-800">{{ $nights }} {{ $nights === 1 ? 'diária' : 'diárias' }}</dd></div><div class="flex justify-between py-4"><dt class="text-sm text-slate-500">Hóspedes</dt><dd class="text-sm font-semibold text-slate-800">{{ $data['adults'] }} adulto(s){{ ($data['children'] ?? 0) ? ', '.$data['children'].' criança(s)' : '' }}</dd></div></dl><div class="border-t border-slate-200 bg-sky-50 px-6 py-5"><p class="text-sm text-slate-600">Valor inicial</p><p class="mt-1 text-2xl font-bold text-slate-900">R$ {{ number_format($totalAmount, 2, ',', '.') }}</p></div></aside>
        <div class="lg:col-span-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('reservations.create') }}" class="rounded-lg border border-slate-300 bg-white px-5 py-2.5 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50">Voltar</a><button type="submit" class="rounded-lg bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-700">Confirmar reserva</button></div>
    </form></div></div>
</x-app-layout>
